// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgayFLoqn3r4A1MxdQ39L3zLRuLlsOteQ',
    appId: '1:843101920444:web:5d4587f8f573c9e089c4b9',
    messagingSenderId: '843101920444',
    projectId: 'picore-app-v1',
    authDomain: 'picore-app-v1.firebaseapp.com',
    storageBucket: 'picore-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlUuLPtpV6OHw8VB9pctkzwktJRbIkn8',
    appId: '1:843101920444:android:f03c9df512b3261089c4b9',
    messagingSenderId: '843101920444',
    projectId: 'picore-app-v1',
    storageBucket: 'picore-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PauqagckljQP50zIWzJG8rpSTkR-pik',
    appId: '1:843101920444:ios:f6ed62d2dd81adaa89c4b9',
    messagingSenderId: '843101920444',
    projectId: 'picore-app-v1',
    storageBucket: 'picore-app-v1.firebasestorage.app',
    iosBundleId: 'com.example.picore',
  );
}
